name: Build QMK firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: Thunderbird2086/qmk_firmware
      qmk_ref: _tb2086

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
