name: Build QMK firmware

on: [pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: Thunderbird2086/qmk_firmware
      qmk_ref: _tb2086
