name: Release QMK firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: Thunderbird2086/qmk_firmware
      qmk_ref: _tb2086

  publish:
    name: 'QMK Userspace Publish'
    if: always() && !cancelled()
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@v4

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        if: always() && !cancelled()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: QMK Firmware - ${{ github.ref_name }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            **/*.hex
            **/*.bin
            **/*.uf2
